logging:
  file: app.log
server:  port: 8080

spring:  application:    name: monolith
  datasource:    url: jdbc:mysql://localhost:3306/db
    username: root
    password: changeit
  jpa:    hibernate:      ddl-auto: update
jwt:
  key-store: classpath:jwt.p12
  key-store-password: changeit
  key-pair-alias: jwt
  key-pair-password: changeit    
  expire:
    in: 36000